import test from 'node:test';
import assert from 'node:assert/strict';
import {PhysicsWorld,Body,Vehicle,collide} from '../src/physics.js';
import {PortfolioWorld} from '../src/world.js';
import {heightAt,normalAt} from '../src/terrain.js';
import {qAxis,qRotate,hex,length} from '../src/math.js';
const dt=1/60;
const step=(world,n)=>{for(let i=0;i<n;i++)world.step(dt);};
function car(){const world=new PhysicsWorld(),vehicle=new Vehicle(world,[0,3,0]);step(world,240);return {world,vehicle};}
function campus(){const engine={mesh(shape,position,scale,color,options={}){return {position:[...position],scale:[...scale],color:hex(color),...options};},textTexture(){return {};}},physics=new PhysicsWorld(),world=new PortfolioWorld(engine,physics),vehicle=new Vehicle(physics);step(physics,120);return {physics,world,vehicle};}

test('heightfield is finite and its normals are normalized',()=>{for(let x=-110;x<=110;x+=11)for(let z=-110;z<=110;z+=11){assert.ok(Number.isFinite(heightAt(x,z)));assert.ok(Math.abs(length(normalAt(x,z))-1)<1e-6);}assert.ok(heightAt(0,0)>heightAt(110,0));});
test('box SAT rejects a separated pair and detects a rotated overlap',()=>{const a=new Body({position:[0,3,0]}),b=new Body({position:[4,3,0]});assert.equal(collide(a,b),null);b.reset([.6,3,0],qAxis([0,1,0],.6));assert.ok(collide(a,b)?.depth>0);});
test('sphere collision works with a box and another sphere',()=>{const a=new Body({position:[0,3,0],radius:1}),b=new Body({position:[1,3,0]});assert.ok(collide(a,b));assert.ok(collide(a,new Body({position:[1,3,0],radius:1})));assert.equal(collide(a,new Body({position:[4,3,0],radius:1})),null);});
test('four suspension rays hold the rover above the terrain',()=>{const {world,vehicle:v}=car();step(world,360);assert.equal(v.grounded,4);assert.ok(v.body.p[1]>2&&v.body.p[1]<2.4);assert.ok(Math.abs(v.body.v[1])<.02);assert.ok(qRotate(v.body.q,[0,1,0])[1]>.999);});
test('forward, reverse and steering respond to tire forces',()=>{const {world,vehicle:v}=car();v.controls.throttle=1;step(world,90);assert.ok(v.body.p[2]<-8);v.controls.steer=1;step(world,90);assert.ok(v.body.p[0]<-4);v.reset([0,3,0]);step(world,120);v.controls.throttle=-1;step(world,120);assert.ok(v.body.p[2]>8);});
test('handbrake stops the car and boost consumes a rechargeable battery',()=>{const {world,vehicle:v}=car();v.controls.throttle=1;v.controls.boost=true;step(world,120);assert.ok(v.battery<.65);assert.ok(v.speed>20);v.controls={throttle:0,steer:0,brake:true,boost:false};step(world,160);assert.ok(Math.abs(v.speed)<.1);assert.ok(v.battery>.8);});
test('jump requires ground contact and returns safely to the ground',()=>{const {world,vehicle:v}=car();assert.equal(v.jump(),true);assert.equal(v.jump(),false);step(world,18);assert.ok(v.body.p[1]>3);assert.equal(v.grounded,0);step(world,240);assert.equal(v.grounded,4);assert.ok(v.body.p[1]<2.4);});
test('building colliders stop sustained full-throttle driving',()=>{const {world,vehicle:v}=car();world.add({position:[0,3,-12],half:[10,3,.25]});v.controls.throttle=1;step(world,500);assert.ok(v.body.p[2]>-10);assert.ok(Math.abs(v.speed)<.1);});
test('car recovers with zero velocity and a normalized orientation',()=>{const {world,vehicle:v}=car();v.controls.throttle=1;step(world,40);v.reset([12,3,18],Math.PI/2);assert.deepEqual(v.body.p,[12,3,18]);assert.deepEqual(v.body.v,[0,0,0]);assert.ok(Math.abs(length(v.body.q)-1)<1e-8);assert.ok(qRotate(v.body.q,[0,0,-1])[0]<-.99);});
test('the built ramp launches the car rather than behaving as flat decoration',()=>{const {physics,vehicle:v}=campus();v.reset([-12,3,58]);step(physics,100);v.controls.throttle=1;let highest=0;for(let i=0;i<230;i++){physics.step(dt);highest=Math.max(highest,v.body.p[1]);}assert.ok(highest>4.5);assert.ok(v.body.p[2]<30);});
test('wheel loads tip the hinged seesaw as the car crosses it',()=>{const {physics,vehicle:v}=campus();const seesaw=physics.dynamicBodies.find(b=>b.tag==='seesaw');v.reset([-35,3,28],-Math.PI/2);step(physics,100);v.controls.throttle=.45;let min=1,max=-1;for(let i=0;i<260;i++){physics.step(dt);min=Math.min(min,seesaw.q[2]);max=Math.max(max,seesaw.q[2]);}assert.ok(max>.09);assert.ok(min<-.05);assert.ok(v.body.p[0]>-18);assert.deepEqual(seesaw.p,seesaw.hinge.anchor);});
test('a collision-driven shot reaches the football goal',()=>{const {physics,vehicle:v,world}=campus();v.reset([55,3,36]);world.ball.reset();step(physics,100);v.controls.throttle=1;let reached=false;for(let i=0;i<220;i++){physics.step(dt);const p=world.ball.p;if(Math.abs(p[0]-55)<3.2&&p[2]<9.25&&p[2]>6.2&&p[1]<4.5)reached=true;}assert.ok(reached);});
test('a drive down the bowling lane knocks over all ten rigid-body pins',()=>{const {physics,vehicle:v,world}=campus();v.reset([-56,3,-21]);world.pins.forEach(p=>p.reset());step(physics,100);v.controls.throttle=1;step(physics,230);const down=world.pins.filter(p=>qRotate(p.q,[0,1,0])[1]<.65||Math.hypot(p.p[0]-p.home.p[0],p.p[2]-p.home.p[2])>.9).length;assert.equal(down,10);physics.resetProps();for(const pin of world.pins)assert.deepEqual(pin.p,pin.home.p);});
