import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {createPortfolioServer} from '../server.mjs';
async function running(t,options={}){const dataDir=await mkdtemp(resolve(tmpdir(),'grove-test-')),server=createPortfolioServer({dataDir,...options});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{await new Promise(r=>server.close(r));await rm(dataDir,{recursive:true,force:true});});return {base:`http://127.0.0.1:${server.address().port}`,dataDir};}
const post=(base,path,data,extra={})=>fetch(base+'/api/'+path,{method:'POST',headers:{'Content-Type':'application/json',...extra},body:JSON.stringify(data)});
test('static server serves the entrypoint, data, modules, CV and original GLBs',async t=>{const {base}=await running(t);for(const path of ['/','/profile.html','/style.css','/3d-view.html','/projects.html','/project-cubeshooter.html','/css/site.css','/js/site.js','/src/app.js','/data/portfolio.json','/assets/models/buggy.glb','/assets/documents/Shehraz-Khalid-CV.pdf']){const r=await fetch(base+path);assert.equal(r.status,200,path);assert.ok((await r.arrayBuffer()).byteLength>30,path);}assert.equal((await fetch(base+'/api/status')).status,503);});
test('private files and directory traversal are not served',async t=>{const {base}=await running(t);for(const path of ['/server.mjs','/server-data/community.json','/src/%2e%2e%2fserver.mjs','/.git/config'])assert.ok((await fetch(base+path)).status>=400,path);});
test('community notes and scores validate, persist, and return escaped-safe data',async t=>{const {base,dataDir}=await running(t,{community:true,rateMs:0});assert.equal((await(await fetch(base+'/api/status')).json()).service,'shehraz-grove');let r=await post(base,'notes',{name:'Visitor',message:'<b>A good drive</b>'});assert.equal(r.status,201);assert.equal((await r.json()).message,'<b>A good drive</b>');r=await post(base,'notes',{name:'',message:'empty name'});assert.equal(r.status,400);r=await post(base,'scores',{name:'Driver',time:83.52,track:'grove-v2'});assert.equal(r.status,201);assert.equal((await(await fetch(base+'/api/scores')).json())[0].time,83.52);assert.equal((await post(base,'scores',{name:'Fake',time:-1,track:'grove-v2'})).status,400);const saved=JSON.parse(await readFile(resolve(dataDir,'community.json'),'utf8'));assert.equal(saved.notes.length,1);assert.equal(saved.scores.length,1);});
test('community writes enforce same origin and rate limiting',async t=>{const {base}=await running(t,{community:true,rateMs:10000});assert.equal((await post(base,'notes',{name:'A',message:'hello'},{Origin:'https://unrelated.test'})).status,403);assert.equal((await post(base,'notes',{name:'A',message:'hello'})).status,201);assert.equal((await post(base,'notes',{name:'A',message:'again'})).status,429);});
