import {readFile,writeFile,mkdir,cp,rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {esc,projectCard,projectDetail,profileContent,careerContent,contactContent,educationContent,skillsContent,mobileContent,publisherContent,featuredProjects} from '../src/portfolio-content.js';
const root=path.resolve(fileURLToPath(new URL('..',import.meta.url)));
const d=JSON.parse(await readFile(path.join(root,'data/portfolio.json'),'utf8'));
const put=(p,c)=>writeFile(path.join(root,p),c);
function shell(title,body,{current='',home=false,description=d.intro}={}){
return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#040a15"><meta name="description" content="${esc(description)}"><title>${esc(title)} | Shehraz Khalid</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="css/site.css"><link rel="stylesheet" href="css/content.css"></head><body><a class="skip-link" href="#main">Skip to content</a><div class="bg-grid" aria-hidden="true"></div><div class="bg-glow" aria-hidden="true"></div><header class="site-header"><div class="header-inner"><a class="nav-logo" href="index.html" aria-label="Shehraz Khalid home">SHEHRAZ<span>.</span></a><button class="mobile-menu-toggle" aria-label="Open navigation" aria-controls="site-nav" aria-expanded="false">&#9776;</button><nav class="site-nav" id="site-nav" aria-label="Main navigation">${[['profile.html','About','profile'],['experience.html','Experience','experience'],['projects.html','Projects','projects'],['contact.html','Contact','contact']].map(([url,label,key])=>`<a href="${url}" ${current===key?'aria-current="page"':''}>${label}</a>`).join('')}<a class="nav-world" href="3d-view.html">3D World &#8599;</a></nav></div></header>${body}<footer class="site-footer"><div class="container"><span>&copy; ${d.updated.slice(0,4)} Shehraz Khalid &middot; Unity / C# / Interactive experiences</span><span><a href="mailto:${esc(d.email)}">Email</a> &nbsp; / &nbsp; <a href="${d.cvPath}" download>CV</a> &nbsp; / &nbsp; <a href="profile.html">Profile</a></span></div></footer><script type="module" src="js/site.js"></script></body></html>`;}
const hero=`<section class="hero"><div class="container"><p class="eyebrow"><span class="status-dot"></span> INITIALIZING_PLAYER_PROFILE...</p><h1 class="glitch-text" data-text="SHEHRAZ KHALID">SHEHRAZ KHALID</h1><h2>BUILDING IMMERSIVE WORLDS.</h2><p class="hero-copy">Unity 2D &amp; 3D games. Custom controllers. Worlds you can play.<br>I'm Shehraz, a software engineer based in Lahore.</p><div class="action-row"><a class="primary-button world-button" href="3d-view.html">ENTER 3D WORLD &#8594;</a><a class="secondary-button" href="${d.cvPath}" download>DOWNLOAD CV &#8595;</a><a class="secondary-button" href="#projects">VIEW MY WORK</a></div><div class="hero-bottom"><span>UNITY &amp; C#</span><span>GAME PHYSICS</span><span>ANDROID / iOS PROJECTS</span></div></div></section>`;
const featured=`<section class="section" id="projects"><div class="container"><div class="section-heading"><div><p class="card-kicker">SELECTED WORK / 01 - 03</p><h2>Featured <span>Projects.</span></h2><p>Three from-scratch builds. Different genres, different systems, the same hands-on approach.</p></div><a class="text-link" href="projects.html">All ${d.projects.length} projects &#8594;</a></div><div class="project-grid">${featuredProjects(d).map(p=>projectCard(p)).join('')}</div><div class="feature-strip"><a href="3d-view.html?stop=career-road"><span class="feature-symbol" aria-hidden="true">18</span><div><h3>A career you can drive through.</h3><p>Follow four chapters, from 2018 onwards.</p></div><span class="arrow">&#8594;</span></a><a href="3d-view.html?stop=projects"><span class="feature-symbol" aria-hidden="true">&#9635;</span><div><h3>Step inside the project exhibition.</h3><p>Tap an icon or screen to explore the work.</p></div><span class="arrow">&#8594;</span></a></div></div></section>`;
const about=`<hr class="section-divider"><section class="section" id="experience"><div class="container about-short"><div><p class="card-kicker">THE PERSON BEHIND THE GAMES</p><h2>Good systems.<br>Better experiences.</h2><p>${esc(d.intro)}</p><div class="about-stats"><div><strong>2018</strong><small>FIRST CV ROLE</small></div><div><strong>4</strong><small>STUDIOS IN THE CV</small></div><div><strong>2D / 3D</strong><small>UNITY DEVELOPMENT</small></div></div><a class="secondary-button" href="profile.html">Read my full profile &#8594;</a></div><div class="short-timeline">${d.careerJourney.map(e=>`<article><time>${esc(e.period)}</time><h3>${esc(e.company)}</h3><p>${esc(e.role)}</p></article>`).join('')}<a class="text-link" href="experience.html">Full experience & responsibilities &#8594;</a></div></div></section>`;
const contact=`<section class="contact-band" id="contact"><div class="container"><div><p class="card-kicker">LET'S BUILD SOMETHING</p><h2>Have an idea in mind?</h2><p>Game development, interactive experiences and the systems behind them.</p></div><a class="primary-button" href="contact.html">GET IN TOUCH &#8599;</a></div></section>`;
await put('index.html',shell('Games Developer',`<main id="main">${hero}${featured}${about}${contact}</main>`,{home:true}));
const categories=[...new Set(d.projects.map(p=>p.category))].sort();
await put('projects.html',shell('Project archive',`<main id="main" class="page-main"><div class="container"><div class="breadcrumbs"><a href="index.html">Home</a><span>/ Projects</span></div><p class="card-kicker">THE PROJECT ARCHIVE</p><h1 class="page-title">A collection of playable ideas.</h1><p class="page-lead">Explore the featured builds and the wider project collection. Search by title, genre or package name. The first three entries are also featured on the homepage.</p><div class="catalog-tools"><label>Search projects<input id="project-search" type="search" placeholder="Try physics, puzzle, thief..." autocomplete="off"></label><label>Genre<select id="project-category"><option value="">All genres</option>${categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select></label><label>Platform<select id="project-platform"><option value="">All platforms</option><option>Android</option><option>iOS</option></select></label></div><div class="catalog-count"><span id="project-count" role="status">${d.projects.length} projects</span><button id="reset-filters" class="text-link">Reset filters</button></div><noscript><p>All projects are shown below. JavaScript is only needed for filtering and the image viewer.</p></noscript><div class="project-grid" id="project-grid">${d.projects.map(p=>projectCard(p)).join('')}</div><div id="empty-projects" class="empty-state" hidden>No matching projects. Try another search or reset the filters.</div>${publisherContent(d)}</div></main>`,{current:'projects'}));
for(const p of d.projects){const body=`<main id="main" class="page-main"><div class="container"><div class="page-narrow"><div class="breadcrumbs"><a href="index.html">Home</a><span>/</span><a href="projects.html">Projects</a><span>/ ${esc(p.title)}</span></div>${projectDetail(p,{headingId:'page-title'})}<div class="action-row"><a class="secondary-button" href="projects.html">&#8592; Back to all projects</a>${d.projects[p.order]?`<a class="text-link" href="${d.projects[p.order].detailPage}">Next project &#8594;</a>`:''}</div></div></div></main>`;await put(p.detailPage,shell(p.title,body,{current:'projects',description:p.summary}));}
const sections=[['profile','Meet Shehraz Khalid',profileContent(d)],['experience','A career built over time.',careerContent(d)],['skills','The tools behind the play.',skillsContent(d)],['mobile','Beyond the core game.',mobileContent(d)],['education','Always learning.',educationContent(d)],['contact',"Let's start a conversation.",contactContent(d)]];
for(const [key,title,body] of sections)await put(key+'.html',shell(title,`<main id="main" class="page-main"><div class="container"><div class="page-narrow"><div class="breadcrumbs"><a href="index.html">Home</a><span>/ ${esc(key)}</span></div><p class="card-kicker">SHEHRAZ KHALID / ${esc(key.toUpperCase())}</p><h1 class="page-title" id="page-title">${esc(title)}</h1>${body}<div class="action-row"><a class="text-link" href="3d-view.html?stop=${key==='profile'?'about':key}">Explore this stop in 3D &#8594;</a></div></div></div></main>`,{current:key}));
await put('.nojekyll','');
await put('404.html',shell('Page not found',`<main id="main" class="page-main"><div class="container"><p class="card-kicker">404 / A LITTLE OFF TRACK</p><h1 class="page-title">Let's get you back on the road.</h1><p>The requested page was not found.</p><div class="action-row"><a class="primary-button" href="index.html">Portfolio home</a><a class="secondary-button" href="projects.html">Project archive</a></div></div></main>`));
if(process.argv.includes('--dist')){
 const out=path.join(root,'dist');await rm(out,{recursive:true,force:true});await mkdir(out);
 const {readdir}=await import('node:fs/promises');for(const name of await readdir(root)){if(name.endsWith('.html')||['style.css','.nojekyll'].includes(name))await cp(path.join(root,name),path.join(out,name));}
 for(const dir of ['css','js','src','data'])await cp(path.join(root,dir),path.join(out,dir),{recursive:true});
 const assets=new Set(['assets/favicon.svg',d.cvPath,'assets/models/buggy.glb','assets/models/tower.glb','assets/models/crystal_tree.glb']);
 for(const p of d.projects)for(const asset of [p.media.icon,p.media.cover,p.media.iconPreview,p.media.coverPreview,...p.media.screenshots.flatMap(s=>[s.src,s.preview])].filter(Boolean))assets.add(asset);
 for(const asset of assets){await mkdir(path.dirname(path.join(out,asset)),{recursive:true});await cp(path.join(root,asset),path.join(out,asset));}
}
console.log(`Built home, ${d.projects.length} project pages, project archive and ${sections.length} profile pages. Featured: ${featuredProjects(d).map(p=>p.id).join(', ')}.`);
