/** Pure, escaped content shared by static pages and the 3D portfolio dialogs. */
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const safeLocal=p=>typeof p==='string'&&!p.startsWith('/')&&!p.includes('..')&&/^[a-zA-Z0-9_./-]+$/.test(p)?p:'';
export const safeExternal=u=>{try{const v=new URL(u);return v.protocol==='https:'?v.href:'';}catch{return '';}};
const ext=(url,label,cls='secondary-button')=>safeExternal(url)?`<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label} <span aria-hidden="true">&#8599;</span></a>`:'';
const pills=items=>`<div class="content-pills">${items.map(t=>`<span>${esc(t)}</span>`).join('')}</div>`;
export const featuredProjects=d=>d.projects.filter(p=>p.featured).sort((a,b)=>a.order-b.order);
export function projectCard(p,{world=false}={}){
 const media=p.media,href=safeLocal(p.detailPage),attrs=world?`href="${href}" data-open-project="${esc(p.id)}"`:`href="${href}"`;
 return `<article class="project-card" data-project-card data-search="${esc([p.title,p.alias,p.category,p.platform,p.packageId].join(' ').toLowerCase())}" data-category="${esc(p.category)}" data-platform="${esc(p.platform)}">
 <a ${attrs} class="project-media" aria-label="Read ${esc(p.title)} project details"><img src="${safeLocal(media.coverPreview||media.cover)}" alt="${esc(p.title)} ${media.status==='local'?'project artwork':'artwork pending'}" loading="lazy" decoding="async"><span class="project-order">${String(p.order).padStart(2,'0')}</span>${p.featured?'<span class="featured-badge">FEATURED</span>':''}</a>
 <div class="project-card-body"><div class="project-identity"><img class="project-icon" src="${safeLocal(media.iconPreview||media.icon)}" alt="" loading="lazy"><div><p class="card-kicker">${esc(p.category)}</p><h3><a ${attrs}>${esc(p.title)}</a></h3></div></div><p class="project-summary">${esc(p.summary)}</p><div class="project-meta"><span>${esc(p.platform)}</span>${p.duration?`<span>${p.durationEstimated?'Est. ':''}${esc(p.duration)}</span>`:''}</div><a ${attrs} class="project-read">Explore project <span aria-hidden="true">&#8594;</span></a></div></article>`;
}
export function projectDetail(p,{world=false,headingId='page-title'}={}){
 const shots=p.media.screenshots;const url=safeExternal(p.storeUrl);
 const gallery=shots.length?`<div class="project-gallery" data-gallery="${esc(p.id)}">${shots.map((s,i)=>`<figure><button type="button" class="gallery-item" data-lightbox="${esc(p.id)}" data-src="${safeLocal(s.src)}" data-caption="${esc(s.caption)}" aria-label="Enlarge ${esc(p.title)} image ${i+1}"><img src="${safeLocal(s.preview||s.src)}" alt="${esc(p.title)} - ${esc(s.caption)}" loading="lazy" decoding="async"><span aria-hidden="true">&#10530;</span></button><figcaption>${esc(s.caption)}</figcaption></figure>`).join('')}</div>`:`<div class="media-pending"><img src="${safeLocal(p.media.cover)}" alt="Artwork not yet available" loading="lazy"><p>Project artwork is not yet in this archive. Only verified local images will appear here.</p></div>`;
 return `<div class="project-detail"><div class="detail-heading"><img src="${safeLocal(p.media.iconPreview||p.media.icon)}" alt="${esc(p.title)} icon" class="detail-icon"><div><p class="card-kicker">PROJECT ${String(p.order).padStart(2,'0')} / ${esc(p.platform)} / ${esc(p.category)}</p><h2 id="${headingId}">${esc(p.title)}</h2>${p.alias?`<p class="muted">Also referred to as ${esc(p.alias)}</p>`:''}</div></div>
 <div class="detail-meta">${p.duration?`<div><small>${p.durationEstimated?'ESTIMATED DEVELOPMENT TIME':'DEVELOPMENT TIME'}</small><strong>${esc(p.duration)}</strong></div>`:''}<div><small>PLATFORM</small><strong>${esc(p.platform)}</strong></div>${p.roleNotes.length?'<div><small>APPROACH</small><strong>Built from scratch</strong></div>':''}</div>
 <p class="lead">${esc(p.summary)}</p><div class="action-row">${ext(url,p.platform==='iOS'?'View App Store listing':'View Google Play listing','primary-button')}${world?`<a class="secondary-button" href="${safeLocal(p.detailPage)}">Open full project page &#8599;</a>`:'<a class="secondary-button" href="3d-view.html?stop=projects">See the 3D exhibition &#8599;</a>'}</div>
 <div class="content-rule"></div><h3>Project gallery <span class="gallery-total">(${shots.length} images)</span></h3>${gallery}
 ${p.roleNotes.length?`<section class="content-section"><p class="card-kicker">PERSONAL DEVELOPMENT NOTES</p><h3>What I built</h3>${p.developmentFocus?'<p>'+esc(p.developmentFocus)+'</p>':''}<div class="note-grid">${p.roleNotes.map((n,i)=>`<article><span class="note-number">0${i+1}</span><p>${esc(n)}</p></article>`).join('')}</div></section>`:''}
 ${p.features.length?`<section class="content-section"><h3>${p.roleNotes.length?'Gameplay & systems':'Gameplay overview'}</h3>${pills(p.features)}</section>`:''}
 <details class="source-details"><summary>Project information & sources</summary><p>${esc(p.developmentSource)}</p><p>${p.source.kind==='archived-store'?'The current store listing is unavailable. This gallery was recovered from an archive matching the exact app ID.':p.source.kind==='unavailable'?'This exact store page could not be verified during the update. The submitted link is preserved; the page does not assume the listing is still available.':'Gameplay overview paraphrased from the matching public store listing. Store copy and release imagery can change over time.'}</p><p>Identifier: <code>${esc(p.packageId)}</code></p><p>Artwork: ${esc(p.media.source)}.</p>${ext(url,'Original source listing','text-link')}${p.source.archiveUrl?ext(p.source.archiveUrl,'Archived listing','text-link'):''}</details></div>`;
}
export function profileContent(d){
 return `<p class="lead">${esc(d.intro)}</p><p>${esc(d.about)}</p><dl class="profile-grid"><div><dt>Full name</dt><dd>${esc(d.name)}</dd></div><div><dt>Role</dt><dd>${esc(d.role)}</dd></div><div><dt>Specialty</dt><dd>${esc(d.specialty)}</dd></div><div><dt>Based in</dt><dd>${esc(d.location)}</dd></div><div><dt>Email</dt><dd><a href="mailto:${esc(d.email)}">${esc(d.email)}</a></dd></div><div><dt>Phone</dt><dd><a href="tel:${esc(d.phone)}">${esc(d.phone)}</a></dd></div><div><dt>LinkedIn</dt><dd>${safeExternal(d.links.linkedin)?ext(d.links.linkedin,'View LinkedIn','text-link'):'<span class="muted">Profile link to be added</span>'}</dd></div>${safeExternal(d.links.github)?`<div><dt>GitHub</dt><dd>${ext(d.links.github,'View GitHub','text-link')}</dd></div>`:''}</dl><div class="action-row"><a class="primary-button" href="${safeLocal(d.cvPath)}" download>Download CV &#8595;</a><a class="secondary-button" href="contact.html">Contact details</a></div><div class="content-rule"></div><h3>Core skills</h3>${pills(d.skills)}<h3>Outside the code</h3>${pills(d.interests)}<h3>Languages</h3>${pills(d.languages.map(l=>`${l.name} / ${l.level}`))}`;
}
export function careerContent(d,{world=false,active=null}={}){
 return `<p class="lead">From my first Unity role in 2018 to team leadership, custom controllers and mobile game systems.</p><div class="action-row">${world?'<button class="primary-button" data-action="travel" data-id="career-road">Drive through my career &#8594;</button>':'<a class="primary-button" href="3d-view.html?stop=career-road">Drive through my career &#8594;</a>'}<a class="secondary-button" href="${safeLocal(d.cvPath)}" download>Download CV</a></div><div class="career-timeline">${d.careerJourney.map((e,i)=>`<article id="${esc(e.id)}" class="career-entry ${active===i?'is-selected':''}"><div class="career-date"><b>${esc(e.year)}</b><small>${esc(e.period)}</small></div><div><p class="card-kicker">CHAPTER 0${i+1}</p><h3>${esc(e.company)}</h3><p class="career-role">${esc(e.role)} &middot; ${esc(e.location)}</p><p>${esc(e.story)}</p>${e.details.length?e.details.map(n=>`<p class="muted">${esc(n)}</p>`).join(''):''}${world?`<button class="text-link" data-action="travel" data-id="${esc(e.id)}">Visit this milestone &#8594;</button>`:''}</div></article>`).join('')}</div><p class="fineprint">Titles, dates and responsibilities follow the supplied CV. "Present" refers to that document; it is not an independently verified employment update.</p>`;
}
export function contactContent(d){
 return `<p class="lead">Have a game, an interactive idea or a technical challenge in mind? Let's start with a conversation.</p><dl class="profile-grid"><div><dt>Email</dt><dd><a href="mailto:${esc(d.email)}">${esc(d.email)}</a></dd></div><div><dt>Phone</dt><dd><a href="tel:${esc(d.phone)}">${esc(d.phone)}</a></dd></div><div><dt>Location</dt><dd>${esc(d.location)}</dd></div><div><dt>LinkedIn</dt><dd>${safeExternal(d.links.linkedin)?ext(d.links.linkedin,'View LinkedIn','text-link'):'Profile link to be added'}</dd></div></dl><div class="action-row"><a class="primary-button" href="mailto:${esc(d.email)}">Write an email &#8599;</a><a class="secondary-button" href="tel:${esc(d.phone)}">Call Shehraz</a><a class="secondary-button" href="${safeLocal(d.cvPath)}" download>Download CV</a></div>${safeExternal(d.links.github)?ext(d.links.github,'GitHub'):''}${safeExternal(d.links.website)?ext(d.links.website,'Website'):''}`;
}
export function educationContent(d){return `<p class="lead">A technical foundation and a curiosity that keeps growing.</p><div class="career-timeline">${d.education.map(e=>`<article class="career-entry"><div class="career-date"><b>${esc(e.year||'Education')}</b>${e.result?`<small>${esc(e.result)}</small>`:''}</div><div><h3>${esc(e.qualification)}</h3><p>${esc(e.institution)}</p><p class="muted">${esc(e.location)}</p></div></article>`).join('')}</div><h3>Languages</h3>${pills(d.languages.map(l=>l.name+' / '+l.level))}<p class="fineprint">No graduation year or completion status has been assumed for the degree where the CV does not specify one.</p>`;}
export function skillsContent(d){return `<p class="lead">Gameplay engineering, responsive controls and interactive systems.</p><h3>Development skills</h3>${pills(d.skills)}<div class="note-grid"><article><h3>Unity 2D & 3D</h3><p>Android games and interactive experiences built using Unity and C#.</p></article><article><h3>Physics & controllers</h3><p>Game physics and controllers developed from scratch, as described in my CV.</p></article><article><h3>Hyper-casual mechanics</h3><p>Design and implementation of focused, approachable game mechanics.</p></article></div><div class="action-row"><a class="primary-button" href="projects.html">Explore the projects</a><a class="secondary-button" href="3d-view.html?stop=test-yard">Try the physics playground</a></div>`;}
export function mobileContent(d){return `<p class="lead">The systems around the game are part of the experience, too.</p><h3>Mobile integrations</h3>${pills(d.integrations)}<div class="note-grid"><article><h3>Mediation</h3><p>Integration experience with AdMob Mediation and MAX Mediation.</p></article><article><h3>Analytics & attribution</h3><p>CV-listed tools include Firebase, ByteBrew, AppLovin and AppsFlyer.</p></article></div><p class="fineprint">Tool names describe CV-listed experience. No unprovided revenue, retention or performance metrics are claimed.</p>`;}
export function publisherContent(d){return d.publisherLinks.map(p=>`<div class="publisher-card"><div><p class="card-kicker">ADDITIONAL PUBLISHER LINK</p><h3>${esc(p.title)}</h3><p class="fineprint">${esc(p.note)}</p></div>${ext(p.url,'Browse publisher','secondary-button')}</div>`).join('');}
