import {profileContent,careerContent,contactContent,educationContent,skillsContent,mobileContent,projectCard,projectDetail,featuredProjects} from './portfolio-content.js';
import {STATIONS,RACE_POINTS,COLLECTIBLE_POINTS,PALETTE} from './world.js';
import {escapeHTML as esc,safeURL,formatTime} from './storage.js';

export const ACHIEVEMENTS=[
 {id:'first-stop',title:'Nice to meet you',description:'Discover your first portfolio stop.',icon:'01'},
 {id:'explorer',title:'The scenic route',description:'Discover all seven portfolio stops.',icon:'07'},
 {id:'first-spark',title:'A bright idea',description:'Collect your first spark.',icon:'+'},
 {id:'collector',title:'Full of ideas',description:'Collect all twelve sparks.',icon:'12'},
 {id:'airtime',title:'Take the leap',description:'Jump the rover into the air.',icon:'^'},
 {id:'bowling',title:'A clean sweep',description:'Knock down all ten bowling pins.',icon:'X'},
 {id:'goal',title:'Goal oriented',description:'Push the ball into the goal.',icon:'O'},
 {id:'lap',title:'One good lap',description:'Finish the twelve-checkpoint circuit.',icon:'F'},
 {id:'distance',title:'Getting somewhere',description:'Drive a total of one kilometre.',icon:'1K'},
 {id:'night',title:'After hours',description:'Explore the campus at night.',icon:'N'},
 {id:'paint',title:'Make it yours',description:'Change the rover paint in the garage.',icon:'C'},
 {id:'horn',title:'A friendly hello',description:'Give the horn a little tap.',icon:'H'}
];
const sectionTitles={about:['01 / THE GARAGE','Hello, I\'m <em>Shehraz.</em>'],experience:['02 / CAREER STUDIO','Good work.<br><em>Built over time.</em>'],skills:['03 / PHYSICS LAB','The tools<br><em>behind the play.</em>'],mobile:['04 / MOBILE WORKS','Small screens.<br><em>Big possibilities.</em>'],education:['05 / LEARNING GARDEN','Always<br><em>learning.</em>'],contact:['06 / SIGNAL TOWER','Let\'s build<br><em>something good.</em>'],projects:['07 / PROJECT GALLERY','The work.<br><em>Up close.</em>']};
const pills=items=>`<div class="pill-row">${items.map(item=>`<span class="pill">${esc(item)}</span>`).join('')}</div>`;
const action=(name,label,extra='',primary=false)=>`<button class="${primary?'primary-button':'secondary-button'}" data-action="${name}" ${extra}>${label}</button>`;
export class UI{
 constructor(data,store,service){
  this.data=data;this.store=store;this.service=service;this.open=false;this.kind=null;this.snapshot=null;this.onAction=()=>{};
  this.panel=document.querySelector('#panel');this.content=document.querySelector('#panel-content');this.backdrop=document.querySelector('#modal-backdrop');this.lastFocus=null;
  document.addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(!button||button.disabled)return;this.onAction(button.dataset.action,button.dataset);});
  document.querySelector('#close-panel').addEventListener('click',()=>this.close());this.backdrop.addEventListener('click',()=>this.close());
  document.addEventListener('keydown',e=>{if(e.key!=='Tab'||!this.open)return;const elements=[...this.panel.querySelectorAll('button:not(:disabled),a[href],input,textarea,select,[tabindex="0"]')].filter(el=>el.offsetParent!==null);if(!elements.length)return;const first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
 }
 setLoading(progress,message){document.querySelector('#load-progress').style.width=`${progress*100}%`;document.querySelector('#load-label').textContent=message;}
 ready(){this.setLoading(1,'World ready. Your keys are waiting.');const b=document.querySelector('#start-button');b.disabled=false;document.querySelector('#start-label').textContent='Let\'s take a drive'; window.dispatchEvent(new Event('portfolio-ready'));}
 show(kind,extra={}){
  this.lastFocus=document.activeElement;this.open=true;this.kind=kind;this.panel.hidden=false;this.backdrop.hidden=false;document.body.classList.add('has-panel');this.panel.classList.toggle('wide',['map','projects','project','experience','career-detail'].includes(kind));
  let kicker='THE GROVE / A LITTLE DETOUR',html='';
  if(sectionTitles[kind]){[kicker]=sectionTitles[kind];html=this.section(kind,extra);}
  else if(kind==='project'){const p=this.data.projects.find(p=>p.id===extra.id);kicker='PROJECT GALLERY / DEVELOPMENT STORY';html=p?projectDetail(p,{world:true,headingId:'panel-title'}):'<h2 id="panel-title">Project not found</h2>';html+='<div class="action-row"><button class="secondary-button" data-action="section" data-id="projects">&#8592; Back to projects</button></div>';}
  else if(kind==='career-detail'){kicker='CAREER ROAD / THE FULL STORY';html='<h2 id="panel-title">A career built <em>over time.</em></h2>'+careerContent(this.data,{world:true,active:extra.index});}
  else if(kind==='map'){kicker='THE GROVE / FIELD GUIDE';html=this.map();}
  else if(kind==='guide'){kicker='THE KEYS / THE BASICS';html=this.guide();}
  else if(kind==='settings'){kicker='MAKE YOURSELF COMFORTABLE';html=this.settings(extra);}
  else if(kind==='garage'){kicker='SK GARAGE / YOUR LITTLE ROVER';html=this.garage(extra);}
  else if(kind==='challenges'){kicker='COLLECT MOMENTS, NOT JUST SPARKS';html=this.challenges();}
  else if(kind==='community'){kicker='THE VISITOR BOOK';html=this.community();}
  else if(kind==='scores'){kicker='GROVE CIRCUIT / LAP BOOK';html=this.scores();}
  else if(kind==='results'){kicker='GROVE CIRCUIT / FINISH LINE';html=this.results(extra);}
  else if(kind==='pause'){kicker='TAKE YOUR TIME';html=`<h2 id="panel-title">A little<br><em>breather.</em></h2><p class="lead">The world can wait. Your drive is paused.</p><div class="action-row">${action('resume','Back to exploring','',true)}${action('map','World map')}${action('settings','Settings')}</div>${this.guideRows()}`;}
  document.querySelector('#panel-kicker').textContent=kicker;this.content.innerHTML=html;this.content.scrollTop=0;document.querySelector('#close-panel').focus({preventScroll:true});
  if(kind==='career-detail'&&Number.isInteger(extra.index))requestAnimationFrame(()=>this.content.querySelector('.is-selected')?.scrollIntoView({block:'start',behavior:'instant'}));
  if(kind==='settings')this.bindSettings();if(kind==='community')this.bindCommunity();if(kind==='scores')this.loadScores();if(kind==='results')this.bindScoreForm(extra.time);
  if(kind==='map'){const canvas=document.querySelector('#big-map');this.drawMap(canvas,this.snapshot,true);canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height,scale=Math.min(canvas.width,canvas.height)/225;if(Math.abs(y-(canvas.height/2-58*scale))<15&&x>canvas.width/2-55*scale&&x<canvas.width/2+57*scale){this.onAction('travel',{id:'career-road'});return;}let best=null,d=Infinity;for(const s of STATIONS){const ds=Math.hypot(x-(canvas.width/2+s.x*scale),y-(canvas.height/2+s.z*scale));if(ds<d){best=s;d=ds;}}if(best&&d<30)this.onAction('travel',{id:best.id});});}
 }
 close(){this.open=false;this.kind=null;this.panel.hidden=true;this.backdrop.hidden=true;document.body.classList.remove('has-panel');if(this.lastFocus?.isConnected)this.lastFocus.focus({preventScroll:true});this.onAction('panel-closed',{});}
 section(kind,extra={}){
  const d=this.data,t=sectionTitles[kind][1];let html=`<h2 id="panel-title">${t}</h2>`;
  html+=`<div class="section-tabs">${STATIONS.map(s=>`<button class="${kind===s.id?'active':''}" data-action="section" data-id="${s.id}">${s.number} ${s.id==='experience'?'Career':s.id==='projects'?'Projects':s.id[0].toUpperCase()+s.id.slice(1)}</button>`).join('')}</div>`;
  const content={about:profileContent,experience:careerContent,skills:skillsContent,mobile:mobileContent,education:educationContent,contact:contactContent};
  if(content[kind])html+=content[kind](d,{world:true,active:extra.index});
  if(kind==='projects')html+=`<p class="lead">Three featured from-scratch builds. Click an image to open the full project story, with gallery and development notes.</p><div class="project-grid">${featuredProjects(d).map(p=>projectCard(p,{world:true})).join('')}</div><div class="action-row"><a class="primary-button" href="projects.html">Browse all ${d.projects.length} projects &#8599;</a><button class="secondary-button" data-action="travel" data-id="projects">Visit the 3D exhibition</button></div><details class="world-project-index"><summary>Open another project here (${d.projects.length-3} more)</summary><div>${d.projects.filter(p=>!p.featured).map(p=>`<button data-open-project="${esc(p.id)}">${String(p.order).padStart(2,'0')} / ${esc(p.title)}</button>`).join('')}</div></details>`;
  const page=kind==='about'?'profile':kind;
  if(kind!=='projects')html+=`<div class="content-rule"></div><a class="text-link" href="${page}.html">Open the complete ${kind==='about'?'profile':kind} page &#8599;</a>`;
  return html;
 }

 map(){return `<h2 id="panel-title">Take the<br><em>scenic route.</em></h2><p class="lead">Seven places. One story. Drive there yourself, or choose a stop to travel instantly.</p><div class="map-layout"><div class="big-map-wrap"><canvas id="big-map" width="680" height="680" aria-label="Map of the seven portfolio locations"></canvas></div><div class="map-list"><button class="map-stop career-map-stop" data-action="travel" data-id="career-road"><span>18</span><span><strong>The Career Road</strong><small>Drive through 2018 onwards</small></span><i>&#8599;</i></button>${STATIONS.map(s=>`<button class="map-stop" data-action="travel" data-id="${s.id}"><span>${s.number}</span><span><strong>${s.name}</strong><small>${s.type}</small></span><i>${this.store.data.visited.includes(s.id)?'&#10003;':'&#8599;'}</i></button>`).join('')}<button class="map-stop" data-action="race"><span>R</span><span><strong>Grove Circuit</strong><small>Start a timed lap</small></span><i>&#8599;</i></button></div></div><div class="action-row">${action('travel','Bowling lane','data-id="bowling"')}${action('travel','Football pitch','data-id="football"')}${action('garage','Customize the rover')}</div><p class="fineprint">Tap a building sign, project screen or year board to open its story. You can also use Enter near a numbered pad. Discoveries and collectibles are saved in this browser.</p>`;}
 guideRows(){return `<table class="controls-table"><tbody>${[['Open a world sign','CLICK / TAP'],['Career journey','MAP > CAREER ROAD'],['Drive / reverse','W A S D / ARROWS'],['Boost','SHIFT'],['Brake / drift','CTRL / B'],['Jump','SPACE'],['Interact','ENTER / E'],['Recover vehicle','R'],['World map','M'],['Garage / photo mode','G / P'],['Camera / night / sound','C / N / L'],['Horn / hydraulics','H / 1 2 3 4']].map(([label,keys])=>`<tr><td>${label}</td><td><kbd>${keys}</kbd></td></tr>`).join('')}</tbody></table>`;}
 guide(){return `<h2 id="panel-title">You've got<br><em>the keys.</em></h2><p class="lead">The car is small. The possibilities are not. Take it slow or give the physics a little test.</p>${this.guideRows()}<div class="section-rule"></div><h3>Make yourself comfortable</h3><p>Drag the world to orbit the camera. Scroll to zoom. In chase mode the camera follows the rover's heading.</p><h3>On a phone or tablet</h3><p>Use the left joystick to steer and drive. The right buttons handle boost, jump, brake and interaction.</p><h3>With a gamepad</h3><p>Left stick steers. Right trigger accelerates; left trigger reverses. A interacts, B boosts, X brakes and Y jumps. Start pauses.</p><div class="action-row">${action('resume','Back to exploring','',true)}<a class="secondary-button" href="profile.html">Read without driving &#8599;</a></div>`;}
 settings(extra){const s=this.store.data;return `<h2 id="panel-title">Your world.<br><em>Your pace.</em></h2><p class="lead">Adjust the feel, or take the easy route.</p><div class="settings-row"><label for="set-audio">Sound<small>Original synthesized engine, horn and chimes</small></label><input id="set-audio" type="checkbox" class="toggle" ${extra.audio?'checked':''}></div><div class="settings-row"><label for="set-night">After-hours lighting<small>A quieter, illuminated campus</small></label><input id="set-night" type="checkbox" class="toggle" ${s.night?'checked':''}></div><div class="settings-row"><label for="set-motion">Reduce decorative motion<small>No bobbing collectibles or animated scenery</small></label><input id="set-motion" type="checkbox" class="toggle" ${s.reducedMotion?'checked':''}></div><div class="settings-row"><label for="set-quality">Rendering quality<small>Low turns off real-time shadows</small></label><select id="set-quality"><option value="high" ${s.quality==='high'?'selected':''}>High</option><option value="low" ${s.quality==='low'?'selected':''}>Low / battery saver</option></select></div><div class="settings-row"><label for="set-camera">Camera<small>Drag to orbit in either mode</small></label><select id="set-camera"><option value="diorama" ${s.camera==='diorama'?'selected':''}>Diorama</option><option value="chase" ${s.camera==='chase'?'selected':''}>Chase</option></select></div><div class="action-row">${action('reset','Recover the rover')}${action('reset-props','Reset playground objects')}${action('guide','Controls & help')}</div><div class="section-rule"></div><h3>Progress &amp; privacy</h3><p>Discoveries, paint, collectibles, settings and your personal best are stored in this browser. Shared notes and scores are only submitted when you use their forms.</p>${action('clear-progress','Clear saved progress')}<p class="fineprint">${this.store.available?'Browser storage is available.':'Storage is unavailable in this browser; this session still works, but progress may not persist.'} ${this.service.online?'The optional community server is connected.':'Community entries are local to this browser when no server is connected.'}</p>`;}
 bindSettings(){for(const [id,key] of [['set-audio','audio'],['set-night','night'],['set-motion','reducedMotion'],['set-quality','quality'],['set-camera','camera']])document.getElementById(id).addEventListener('change',e=>this.onAction('setting',{key,value:e.target.type==='checkbox'?e.target.checked:e.target.value}));}
 garage(extra){const s=this.store.data,unlocked=s.collected.length>=6,colors=[['#c2df74','Citrus'],['#609b90','Lagoon'],['#d88766','Terracotta'],['#eee5ce','Linen'],['#d9b663','Golden hour']];return `<h2 id="panel-title">Make it<br><em>your own.</em></h2><p class="lead">An original little electric rover with a little room for personality.</p><h3>Pick your paint</h3><div class="paint-options">${colors.map(([color,name],i)=>`<button class="paint-chip ${s.paint===color?'active':''}" style="--paint:${color}" data-action="paint" data-color="${color}" aria-label="${name}${i===4&&!unlocked?' - collect 6 sparks to unlock':''}" title="${name}${i===4&&!unlocked?' / unlock with 6 sparks':''}" ${i===4&&!unlocked?'disabled':''}></button>`).join('')}</div><p class="fineprint">Golden hour unlocks after six sparks. ${Math.min(s.collected.length,6)} / 6 collected.</p><h3>Choose your body style</h3><div class="model-options"><button class="model-option ${s.model==='rover'?'active':''}" data-action="model" data-model="rover"><span class="car-glyph">[SK]</span><strong>Grove Rover</strong><small>NEW ORIGINAL DESIGN<br>ROOF RACK / ANIMATED WHEELS</small></button><button class="model-option ${s.model==='classic'?'active':''}" data-action="model" data-model="classic" ${!extra.originalAvailable?'disabled':''}><span class="car-glyph">[01]</span><strong>Classic Buggy</strong><small>YOUR SUPPLIED GLB<br>NEW PHYSICS / NEW WHEELS</small></button></div><p class="fineprint">Both vehicles share the same suspension, tire forces and collision body. The original GLB body geometry is preserved; the new vehicle system supplies animated wheels and editable body paint.</p><div class="action-row">${action('resume','Take it for a drive','',true)}${action('photo','Try photo mode')}</div>`;}
 challenges(){const s=this.store.data;return `<h2 id="panel-title">Little detours.<br><em>Good stories.</em></h2><p class="lead">There is no rush. A few things to try while you're here.</p><div class="stat-grid"><div class="stat"><strong>${s.visited.length}/7</strong><small>PLACES<br>DISCOVERED</small></div><div class="stat"><strong>${s.collected.length}/12</strong><small>SPARKS<br>COLLECTED</small></div><div class="stat"><strong>${s.achievements.length}/12</strong><small>MOMENTS<br>UNLOCKED</small></div></div><div class="achievement-list">${ACHIEVEMENTS.map(a=>`<div class="achievement ${s.achievements.includes(a.id)?'unlocked':''}"><span>${s.achievements.includes(a.id)?'&#10003;':a.icon}</span><div><strong>${a.title}</strong><small>${a.description}</small></div></div>`).join('')}</div><div class="action-row">${action('race','Take a timed lap','',true)}${action('scores','Lap book')}${action('community','Visitor book')}</div>`;}
 community(){return `<h2 id="panel-title">Leave a<br><em>little hello.</em></h2><span class="mode-badge">${this.service.online?'SHARED VISITOR BOOK':'LOCAL NOTES / THIS BROWSER ONLY'}</span><p class="lead">A thought, a hello, or your favourite little corner of the world.</p><form id="note-form" class="form-grid"><label>Your name<input name="name" required maxlength="24" placeholder="A fellow explorer" autocomplete="nickname"></label><label>Your note<textarea name="message" required maxlength="140" placeholder="I took the scenic route..."></textarea></label><button class="primary-button" type="submit">${this.service.online?'Leave a public note':'Save a local note'} &#8594;</button><p class="form-status" role="status"></p></form><p class="fineprint">${this.service.online?'Notes are public. Do not post personal contact information. The latest 40 notes are kept on this site\'s server.':'No backend is connected. Notes stay on this device and are not visible to other visitors.'}</p><div class="section-rule"></div><div id="notes-list"><p>Opening the notebook...</p></div>`;}
 async bindCommunity(){const form=document.querySelector('#note-form');form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button'),status=form.querySelector('.form-status');button.disabled=true;try{const name=form.elements.name.value.trim(),message=form.elements.message.value.trim();if(!name||!message)throw new Error('Please add a name and a note.');await this.service.post('notes',{name,message});form.reset();status.textContent=this.service.online?'Your public note has been saved.':'Saved on this browser only.';this.loadNotes();}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});this.loadNotes();}
 async loadNotes(){try{const notes=await this.service.get('notes'),el=document.querySelector('#notes-list');if(el)el.innerHTML=notes.length?notes.map(n=>`<article class="note-item"><strong>${esc(n.name)}</strong><time>${esc(new Date(n.createdAt).toLocaleDateString())}</time><p>${esc(n.message)}</p></article>`).join(''):'<p class="fineprint">A fresh page. You can be the first to say hello.</p>';}catch(e){const el=document.querySelector('#notes-list');if(el)el.textContent=e.message;}}
 scores(){return `<h2 id="panel-title">One more<br><em>good lap.</em></h2><span class="mode-badge">${this.service.online?'SHARED LAP BOOK':'LOCAL LAP BOOK / THIS BROWSER'}</span><p class="lead">Twelve checkpoints, a few good corners and a personal best to chase.</p><p class="result-time">${formatTime(this.store.data.bestLap)}</p><p class="result-best">YOUR SAVED PERSONAL BEST</p><div id="scores-list"><p>Opening the lap book...</p></div><div class="action-row">${action('race','Start a lap','',true)}</div><p class="fineprint">Shared lap times are friendly, client-submitted records, not verified competitive results.</p>`;}
 async loadScores(){try{const scores=await this.service.get('scores'),el=document.querySelector('#scores-list');scores.sort((a,b)=>a.time-b.time);if(el)el.innerHTML=scores.length?`<table class="score-table"><tbody>${scores.slice(0,20).map((s,i)=>`<tr><td>${String(i+1).padStart(2,'0')}</td><td>${esc(s.name)}</td><td>${formatTime(s.time)}</td></tr>`).join('')}</tbody></table>`:'<p class="fineprint">No submitted laps yet.</p>';}catch(e){const el=document.querySelector('#scores-list');if(el)el.textContent=e.message;}}
 results(extra){return `<h2 id="panel-title">That was<br><em>a good run.</em></h2><p class="lead">Twelve checkpoints. One full lap of the Grove.</p><p class="result-time">${formatTime(extra.time)}</p><p class="result-best">${extra.best?'NEW PERSONAL BEST':'BEST / '+formatTime(this.store.data.bestLap)}</p><span class="mode-badge">${this.service.online?'OPTIONAL SHARED LAP BOOK':'LOCAL LAP BOOK / THIS BROWSER'}</span><form id="score-form" class="form-grid"><label>Name for this lap<input name="name" required maxlength="24" placeholder="A fellow explorer" autocomplete="nickname"></label><button class="primary-button" type="submit">${this.service.online?'Submit this lap':'Save to local lap book'}</button><p class="form-status" role="status"></p></form><div class="action-row">${action('race','One more lap')}${action('resume','Keep exploring')}</div>`;}
 bindScoreForm(time){const form=document.querySelector('#score-form');form.addEventListener('submit',async e=>{e.preventDefault();const b=form.querySelector('button'),s=form.querySelector('.form-status');b.disabled=true;try{await this.service.post('scores',{name:form.elements.name.value.trim(),time,track:'grove-v2'});s.textContent=this.service.online?'Your lap has been submitted.':'Your lap has been saved on this browser.';b.textContent='Saved';}catch(error){s.textContent=error.message;b.disabled=false;}});}
 toast(title,description='',icon='+'){const el=document.createElement('div');el.className='toast';el.innerHTML=`<span>${esc(icon)}</span><div><strong>${esc(title)}</strong>${description?`<small>${esc(description)}</small>`:''}</div>`;const stack=document.querySelector('#toast-stack');stack.append(el);while(stack.children.length>(innerWidth<761?2:3))stack.firstElementChild.remove();setTimeout(()=>{el.classList.add('out');setTimeout(()=>el.remove(),350);},3800);}
 update(snapshot){this.snapshot=snapshot;const s=this.store.data;document.querySelector('#speed').textContent=Math.round(Math.abs(snapshot.speed)*3.6);document.querySelector('#gear').textContent=Math.abs(snapshot.speed)<.3?'N':snapshot.speed>0?'D':'R';document.querySelector('#boost-percent').textContent=`${Math.round(snapshot.battery*100)}%`;document.querySelector('#boost-meter').style.width=`${snapshot.battery*100}%`;document.querySelector('#visited-count').textContent=`${s.visited.length} / 7 places discovered`;document.querySelector('#token-count').textContent=`${s.collected.length} / 12 sparks`;document.querySelector('#journey-progress').style.width=`${s.visited.length/7*100}%`;document.querySelector('#achievement-count').textContent=s.achievements.length;
  const next=STATIONS.find(st=>!s.visited.includes(st.id));document.querySelector('#journey-label').textContent=next?next.id==='about'?'Meet the maker':`Next: ${next.name}`:'The world is yours';
  const prompt=document.querySelector('#interact-prompt');prompt.hidden=!snapshot.nearby||this.open||!!snapshot.race;if(snapshot.nearby){document.querySelector('#interact-label').textContent=snapshot.nearby.name;document.querySelector('#interact-category').textContent=snapshot.nearby.category||'DISCOVER';}
  const rh=document.querySelector('#race-hud');rh.hidden=!snapshot.race;if(snapshot.race){document.querySelector('#race-time').textContent=formatTime(snapshot.race.elapsed);document.querySelector('#race-checkpoint').textContent=`${snapshot.race.passed} / 12 CHECKPOINTS`;}
  const count=document.querySelector('#countdown');count.hidden=!snapshot.countdown;if(snapshot.countdown)count.textContent=snapshot.countdown;
  this.drawMap(document.querySelector('#mini-map'),snapshot,false);if(this.kind==='map')this.drawMap(document.querySelector('#big-map'),snapshot,true);
 }
 drawMap(canvas,snapshot,big=false){if(!canvas)return;const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,k=Math.min(w,h)/225,cx=w/2,cy=h/2,pt=(x,z)=>[cx+x*k,cy+z*k];ctx.clearRect(0,0,w,h);ctx.fillStyle=big?'#e5ecdc':'#edf1e2';ctx.fillRect(0,0,w,h);ctx.fillStyle='#d1dfc3';ctx.beginPath();ctx.ellipse(cx,cy,105*k,104*k,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#aebd9d';ctx.lineWidth=6*k;ctx.beginPath();for(let i=0;i<=72;i++){const a=i/72*Math.PI*2;ctx.lineTo(...pt(Math.sin(a)*76,Math.cos(a)*69));}ctx.stroke();ctx.strokeStyle='#b6c3a6';ctx.lineWidth=4*k;for(const [a,b] of [[[-59,7],[58,7]],[[0,-61],[0,57]],[[-46,45],[45,45]],[[-45,-31],[44,-31]],[[-45,-30],[-45,48]],[[34,-30],[34,46]]]){ctx.beginPath();ctx.moveTo(...pt(...a));ctx.lineTo(...pt(...b));ctx.stroke();}
  ctx.strokeStyle='#c7a16f';ctx.lineWidth=5*k;ctx.beginPath();ctx.moveTo(...pt(-53,-58));ctx.lineTo(...pt(56,-58));ctx.stroke();for(const chapter of this.data.careerJourney){const [x,y]=pt(chapter.x,-58);ctx.fillStyle='#9c6a41';ctx.beginPath();ctx.arc(x,y,big?4:2.5,0,Math.PI*2);ctx.fill();if(big){ctx.font='9px Arial';ctx.textAlign='center';ctx.fillText(chapter.year,x,y-13);}}
  for(const s of STATIONS){const [x,z]=s.building;ctx.fillStyle='#9daf94';ctx.fillRect(cx+(x-7)*k,cy+(z-5)*k,14*k,10*k);}
  ctx.fillStyle='#91b8ab';ctx.beginPath();ctx.ellipse(...pt(17,20),8*k,7*k,0,0,Math.PI*2);ctx.fill();
  if(big)for(let i=0;i<COLLECTIBLE_POINTS.length;i++)if(!this.store.data.collected.includes(i)){const [x,z]=pt(...COLLECTIBLE_POINTS[i]);ctx.fillStyle='#a0ba6f';ctx.fillRect(x-2.5,z-2.5,5,5);}
  for(const s of STATIONS){const [x,y]=pt(s.x,s.z),visited=this.store.data.visited.includes(s.id);ctx.fillStyle=visited?'#58764b':'#f3f4e7';ctx.strokeStyle=visited?'#58764b':'#7f9670';ctx.lineWidth=big?2:1.4;ctx.beginPath();ctx.arc(x,y,big?12:6.5,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=visited?'#eff5de':'#658053';ctx.font=`${big?10:6}px Consolas,monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(s.number,x,y+.5);}
  if(snapshot?.race){const [x,z]=RACE_POINTS[snapshot.race.next%12];ctx.strokeStyle='#c88553';ctx.lineWidth=big?3:2;ctx.beginPath();ctx.arc(...pt(x,z),big?15:8,0,Math.PI*2);ctx.stroke();}
  if(snapshot?.position){const [x,z]=snapshot.position,[px,py]=pt(x,snapshot.position[2]);const f=snapshot.forward||[0,0,-1];ctx.save();ctx.translate(px,py);ctx.rotate(Math.atan2(f[0],-f[2]));ctx.fillStyle='#294a38';ctx.strokeStyle='#edf4df';ctx.lineWidth=big?2:1.5;const size=big?10:6;ctx.beginPath();ctx.moveTo(0,-size);ctx.lineTo(size*.66,size*.8);ctx.lineTo(0,size*.45);ctx.lineTo(-size*.66,size*.8);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}
  ctx.fillStyle='#879c79';ctx.textAlign='right';ctx.font=`${big?12:7}px Consolas,monospace`;ctx.fillText('N',w-10,big?20:10);ctx.fillText('^',w-10,big?34:20);
 }
}

